package com.itboy.dj.examtool.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.itboy.dj.examtool.local.UserMsg;

import com.itboy.dj.examtool.local.UserMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userMsgDaoConfig;

    private final UserMsgDao userMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userMsgDaoConfig = daoConfigMap.get(UserMsgDao.class).clone();
        userMsgDaoConfig.initIdentityScope(type);

        userMsgDao = new UserMsgDao(userMsgDaoConfig, this);

        registerDao(UserMsg.class, userMsgDao);
    }
    
    public void clear() {
        userMsgDaoConfig.clearIdentityScope();
    }

    public UserMsgDao getUserMsgDao() {
        return userMsgDao;
    }

}
